export const MODEL_SCHEMA = 'local-shell-model/v1';
export const RESULT_SCHEMA = 'local-shell-result/v1';
export const FORMULATION = 'CST_DKT_TRI3_THIN_SHELL_V1';
export const DKT_FORMULATION = 'DKT_CLASSIC_TRI3_V1';
export const ENGINEERING_LEVEL = 'LINEAR_2_5D_THIN_SHELL_CST_DKT_ONLY';

export const DOFS = Object.freeze(['UX', 'UY', 'UZ', 'R1', 'R2']);
export const SURFACES = Object.freeze(['BOTTOM', 'MIDSURFACE', 'TOP']);
export const PRESSURE_SENSES = Object.freeze([
  'ALONG_ELEMENT_NORMAL',
  'OPPOSITE_ELEMENT_NORMAL',
]);

export const QUALIFICATION_STATES = Object.freeze({
  ACCEPTED: 'ACCEPTED',
  REJECTED_MODEL: 'REJECTED_MODEL',
  REJECTED_LOAD_CASE: 'REJECTED_LOAD_CASE',
  UNSUPPORTED_REQUEST: 'UNSUPPORTED_REQUEST',
  SINGULAR_SYSTEM: 'SINGULAR_SYSTEM',
  NUMERICAL_FAILURE: 'NUMERICAL_FAILURE',
});

export const CANONICAL_UNITS = Object.freeze({
  length: 'mm',
  force: 'N',
  moment: 'N*mm',
  pressure: 'MPa',
  modulus: 'MPa',
  rotation: 'rad',
});

export const DKT_INTEGRATION = Object.freeze([
  Object.freeze({ integrationPointId: 'DKT-IP-1', barycentric: Object.freeze([2 / 3, 1 / 6, 1 / 6]), weight: 1 / 3 }),
  Object.freeze({ integrationPointId: 'DKT-IP-2', barycentric: Object.freeze([1 / 6, 2 / 3, 1 / 6]), weight: 1 / 3 }),
  Object.freeze({ integrationPointId: 'DKT-IP-3', barycentric: Object.freeze([1 / 6, 1 / 6, 2 / 3]), weight: 1 / 3 }),
]);

export const FORMULA_IDS = Object.freeze({
  NODE_BASIS: 'LAFEA4.NODE_BASIS_QUALIFICATION/v1',
  FACET_FRAME: 'LAFEA4.CANONICAL_FACET_FRAME/v1',
  CST_MEMBRANE: 'LAFEA4.CST_MEMBRANE_STIFFNESS/v1',
  DKT_EDGE: 'LAFEA4.DKT_EDGE_KIRCHHOFF_CONSTRAINT/v1',
  DKT_CURVATURE: 'LAFEA4.DKT_CLASSIC_CURVATURE/v1',
  DKT_INTEGRATION: 'LAFEA4.DKT_FIXED_THREE_POINT_INTEGRATION/v1',
  BASIS_TRANSFORMATION: 'LAFEA4.RIGID_PRESERVING_FIVE_DOF_TRANSFORMATION/v1',
  GLOBAL_ASSEMBLY: 'LAFEA4.GLOBAL_STIFFNESS_ASSEMBLY/v1',
  NODAL_LOAD: 'LAFEA4.NODAL_FORCE_TANGENT_MOMENT/v1',
  PRESSURE_LOAD: 'LAFEA4.UNIFORM_ELEMENT_NORMAL_PRESSURE/v1',
  PARTITION: 'LAFEA4.EXACT_PRESCRIBED_DOF_PARTITION/v1',
  CHOLESKY: 'LAFEA4.DETERMINISTIC_DENSE_CHOLESKY/v1',
  PCG: 'LAFEA4.DETERMINISTIC_JACOBI_PCG_RELIABLE_RESIDUAL/v1',
  REACTION: 'LAFEA4.REACTION_KQ_MINUS_F/v1',
  STRESS_RECOVERY: 'LAFEA4.THROUGH_THICKNESS_STRESS_RECOVERY/v1',
  INVARIANTS: 'LAFEA4.SAME_POINT_IN_PLANE_INVARIANTS/v1',
  ENERGY: 'LAFEA4.SHELL_STRAIN_ENERGY/v1',
});

export const BASE_LIMITATIONS = Object.freeze([
  'NO_DRILLING_DOF',
  'NO_DRILLING_PENALTY_OR_ARTIFICIAL_STIFFNESS',
  'NO_REISSNER_MINDLIN_TRANSVERSE_SHEAR',
  'NO_SHEAR_CORRECTION_FACTOR',
  'NO_THICK_SHELL_CLAIM',
  'NO_CONTACT_OR_FRICTION',
  'NO_LARGE_DISPLACEMENT',
  'NO_PLASTICITY',
  'NO_MATERIAL_NONLINEARITY',
  'NO_BUCKLING',
  'NO_FATIGUE',
  'NO_CRACK_OR_FRACTURE',
  'NO_AUTOMATIC_OR_ADAPTIVE_MESHING',
  'NO_ATTACHMENT_TEMPLATE',
  'NO_WELD_STRESS',
  'NO_CODE_COMPLIANCE',
  'NO_NODAL_STRESS',
  'NO_STRESS_AVERAGING_OR_SMOOTHING',
  'NO_STRESS_EXTRAPOLATION',
  'NO_CONTOUR_AUTHORITY',
  'NO_UI_OR_APPLICATION_INTEGRATION',
]);

export const RESULT_REQUEST = Object.freeze({
  stressSurfaces: SURFACES,
  dktIntegrationRule: 'FIXED_THREE_POINT_DEGREE_TWO',
  retainElementMatrices: true,
});
