import { canonicalStringify, deepFreeze, semanticHash, stringValue } from '../shared-piping-model/index.js';
import {
  CONSUMER_IDS, IMPLEMENTATION_STATUS, WORKSPACE_CONSUMER_REGISTRY_SCHEMA,
  WORKSPACE_CONSUMER_REGISTRY_V2_SCHEMA, WORKSPACE_CONSUMER_REGISTRY_V3_SCHEMA,
  WORKSPACE_CONSUMER_REGISTRY_V4_SCHEMA, WORKSPACE_CONSUMER_REGISTRY_V5_SCHEMA,
  WORKSPACE_CONSUMER_REGISTRY_V6_SCHEMA, WORKSPACE_CONSUMER_REGISTRY_V7_SCHEMA,
  WORKSPACE_CONSUMER_REGISTRY_V8_SCHEMA, WORKSPACE_CONSUMER_REGISTRY_V9_SCHEMA,
  WORKSPACE_CONSUMER_REGISTRY_V10_SCHEMA, WORKSPACE_CONSUMER_REGISTRY_V11_SCHEMA,
  WORKSPACE_CONSUMER_REGISTRY_V12_SCHEMA,
} from './constants.js';
export function createWorkspaceConsumerRegistry(){return canonicalRegistry(1);}export function createWorkspaceConsumerRegistryV2(){return canonicalRegistry(2);}export function createWorkspaceConsumerRegistryV3(){return canonicalRegistry(3);}export function createWorkspaceConsumerRegistryV4(){return canonicalRegistry(4);}export function createWorkspaceConsumerRegistryV5(){return canonicalRegistry(5);}export function createWorkspaceConsumerRegistryV6(){return canonicalRegistry(6);}export function createWorkspaceConsumerRegistryV7(){return canonicalRegistry(7);}export function createWorkspaceConsumerRegistryV8(){return canonicalRegistry(8);}export function createWorkspaceConsumerRegistryV9(){return canonicalRegistry(9);}export function createWorkspaceConsumerRegistryV10(){return canonicalRegistry(10);}export function createWorkspaceConsumerRegistryV11(){return canonicalRegistry(11);}export function createWorkspaceConsumerRegistryV12(){return canonicalRegistry(12);}
export function validateWorkspaceConsumerRegistry(value){const valid=[1,2,3,4,5,6,7,8,9,10,11,12].map(canonicalRegistry).some((row)=>canonicalStringify(value)===canonicalStringify(row));return deepFreeze({ok:valid,errors:valid?[]:['Workspace consumer registry does not match a closed supported registry version.']});}
export const validateWorkspaceConsumerRegistryV1=(value)=>validateExact(value,canonicalRegistry(1),WORKSPACE_CONSUMER_REGISTRY_SCHEMA);export const validateWorkspaceConsumerRegistryV2=(value)=>validateExact(value,canonicalRegistry(2),WORKSPACE_CONSUMER_REGISTRY_V2_SCHEMA);export const validateWorkspaceConsumerRegistryV3=(value)=>validateExact(value,canonicalRegistry(3),WORKSPACE_CONSUMER_REGISTRY_V3_SCHEMA);export const validateWorkspaceConsumerRegistryV4=(value)=>validateExact(value,canonicalRegistry(4),WORKSPACE_CONSUMER_REGISTRY_V4_SCHEMA);export const validateWorkspaceConsumerRegistryV5=(value)=>validateExact(value,canonicalRegistry(5),WORKSPACE_CONSUMER_REGISTRY_V5_SCHEMA);export const validateWorkspaceConsumerRegistryV6=(value)=>validateExact(value,canonicalRegistry(6),WORKSPACE_CONSUMER_REGISTRY_V6_SCHEMA);export const validateWorkspaceConsumerRegistryV7=(value)=>validateExact(value,canonicalRegistry(7),WORKSPACE_CONSUMER_REGISTRY_V7_SCHEMA);export const validateWorkspaceConsumerRegistryV8=(value)=>validateExact(value,canonicalRegistry(8),WORKSPACE_CONSUMER_REGISTRY_V8_SCHEMA);export const validateWorkspaceConsumerRegistryV9=(value)=>validateExact(value,canonicalRegistry(9),WORKSPACE_CONSUMER_REGISTRY_V9_SCHEMA);export const validateWorkspaceConsumerRegistryV10=(value)=>validateExact(value,canonicalRegistry(10),WORKSPACE_CONSUMER_REGISTRY_V10_SCHEMA);export const validateWorkspaceConsumerRegistryV11=(value)=>validateExact(value,canonicalRegistry(11),WORKSPACE_CONSUMER_REGISTRY_V11_SCHEMA);export const validateWorkspaceConsumerRegistryV12=(value)=>validateExact(value,canonicalRegistry(12),WORKSPACE_CONSUMER_REGISTRY_V12_SCHEMA);
export function workspaceConsumerDescriptor(registry,consumerId){if(!validateWorkspaceConsumerRegistry(registry).ok)throw new TypeError('Workspace consumer registry is invalid.');const descriptor=registry.consumers.find((row)=>row.consumerId===consumerId);if(!descriptor)throw new TypeError(`Unknown workspace consumer: ${consumerId}.`);return descriptor;}
function canonicalRegistry(version){const consumers=descriptorRows(version).map(normalizeDescriptor).sort((a,b)=>a.consumerId.localeCompare(b.consumerId)),base={schema:registrySchema(version),consumers};return deepFreeze({...base,semanticHash:semanticHash(base)});}
function descriptorRows(version){if(version===11)return advancedRows(11);if(version===12)return advancedRows(12);const current=[row(CONSUMER_IDS.WORKSPACE,'Workspace','Current model review and explicit analysis actions.',IMPLEMENTATION_STATUS.IMPLEMENTED,[],allContracts(),workspaceActions(),'EXISTING_CONTRACT_CLAIMS_ONLY'),row(CONSUMER_IDS.REPORTS,'Reports','Review and export the active archived W10.7 package report.',IMPLEMENTATION_STATUS.IMPLEMENTED,reportsRequired(),reportsOptional(),reportsActions(),'ARCHIVED_REPORT_EVIDENCE_ONLY'),loadCalcRow(version),threeDCalcRow(version),pipeSolverRow(version),version>=9?qaRow():row(CONSUMER_IDS.QA,'QA','Future contract quality-assurance consumer.',IMPLEMENTATION_STATUS.NOT_IMPLEMENTED,['sharedModel'],allContracts().filter((key)=>key!=='sharedModel'),[],'NO_ENGINEERING_CLAIMS'),row(CONSUMER_IDS.DEBUG,'Debug','Future read-only contract inspection consumer.',IMPLEMENTATION_STATUS.NOT_IMPLEMENTED,[],allContracts(),[],'NO_ENGINEERING_CLAIMS')];if(version<5)return current;return[row(CONSUMER_IDS.HOME,'Home','Application status and navigation for the recovered Workspace shell.',IMPLEMENTATION_STATUS.IMPLEMENTED,[],[],[],'NO_ENGINEERING_CLAIMS'),...current,version>=6?pcfRow():recoveryRow(CONSUMER_IDS.PCF,'PCF','PCF intake and review recovery has not yet been migrated.'),version>=8?sketcherRow():recoveryRow(CONSUMER_IDS.SKETCHER,'Sketcher','Sketcher capabilities have not yet been migrated to the current runtime.'),version>=10?localFeaRow():null,version>=7?settingsRow():recoveryRow(CONSUMER_IDS.SETTINGS,'Settings','Settings authority has not yet been migrated to the current runtime.')].filter(Boolean);}
function advancedRows(version=12){const rows=[
  row(CONSUMER_IDS.WORKSPACE,'Workspace','Authoritative dataset, model, topology, restraint and load-evidence workspace.',IMPLEMENTATION_STATUS.IMPLEMENTED,[],allContracts(),workspaceActions(),'AUTHORITATIVE_WORKSPACE_MODEL_AND_EVIDENCE'),
  loadCalcRow(11),
  row(CONSUMER_IDS.LAFEA,'LAFEA','Independent local-attachment FEA stages LAFEA.1 through LAFEA.5.',IMPLEMENTATION_STATUS.IMPLEMENTED,[],[],['IMPORT_LAFEA_DOCUMENT','EXPORT_LAFEA_DOCUMENT','RUN_LAFEA','UNDO_LAFEA_EDIT','REDO_LAFEA_EDIT'],'INDEPENDENT_LAFEA_DOCUMENT_AND_QUALIFIED_KERNELS_ONLY'),
  row(CONSUMER_IDS.LFEA,'LFEA','Independent continuum finite-element editor, solver, review and evidence export.',IMPLEMENTATION_STATUS.IMPLEMENTED,[],[],['IMPORT_LFEA_DOCUMENT','EXPORT_LFEA_DOCUMENT','RUN_LFEA','UNDO_LFEA_EDIT','REDO_LFEA_EDIT'],'INDEPENDENT_LFEA_DOCUMENT_AND_QUALIFIED_KERNELS_ONLY'),
];
if(version>=12){
  rows.push(row(CONSUMER_IDS.EMPIRICAL,'Empirical','Independent analytical calculation for attachment foundation (LAFEA.1) and pipe-section screening (LAFEA.2) without finite-element meshing.',IMPLEMENTATION_STATUS.IMPLEMENTED,[],[],['IMPORT_LAFEA_DOCUMENT','EXPORT_LAFEA_DOCUMENT','RUN_LAFEA','UNDO_LAFEA_EDIT','REDO_LAFEA_EDIT'],'INDEPENDENT_LAFEA_DOCUMENT_AND_QUALIFIED_KERNELS_ONLY'));
}
return rows;}
function pcfRow(){return row(CONSUMER_IDS.PCF,'PCF','Stage, parse, review, export and explicitly adopt PCF source into Workspace.',IMPLEMENTATION_STATUS.IMPLEMENTED,[],[],['SELECT_PCF_SOURCE','PARSE_PCF_SOURCE','CANCEL_PCF_INTAKE','ADOPT_PCF_INTAKE','EXPORT_PCF_REVIEW'],'SOURCE_INTAKE_AND_EXPLICIT_WORKSPACE_ADOPTION_ONLY');}
function sketcherRow(){return row(CONSUMER_IDS.SKETCHER,'Sketcher','Create, review, validate, export and explicitly adopt deterministic pipe-centerline drafts.',IMPLEMENTATION_STATUS.IMPLEMENTED,[],['sharedModel','topologyGraph','topologyAudit'],['ADOPT_DRAFT_TO_WORKSPACE','CREATE_EMPTY_DRAFT','DELETE_SKETCH_ENTITY','DRAW_PIPE_SEGMENT','EXPORT_SKETCH_DOCUMENT','IMPORT_SKETCH_DOCUMENT','IMPORT_WORKSPACE_GEOMETRY','MOVE_SKETCH_NODE','REDO_SKETCH_EDIT','RESET_SKETCH_DRAFT','SET_SKETCH_WORKING_PLANE','UNDO_SKETCH_EDIT','VALIDATE_SKETCH_DRAFT'],'DRAFT_GEOMETRY_AND_EXPLICIT_WORKSPACE_ADOPTION_ONLY');}
function localFeaRow(){return row(CONSUMER_IDS.LOCAL_FEA,'Local FEA','Import and review qualified LFEA engineering-review or evidence-export artifacts without modifying engineering evidence.',IMPLEMENTATION_STATUS.IMPLEMENTED,[],[],['IMPORT_LFEA_REVIEW_SOURCE','CLEAR_LFEA_REVIEW_SOURCE','SELECT_LFEA_REVIEW_SECTION','SELECT_LFEA_REVIEW_RECORD','SET_LFEA_RESULT_MODE','SET_LFEA_STRESS_COMPONENT','SET_LFEA_LAYER_VISIBILITY','SET_LFEA_TABLE_PAGE','DOWNLOAD_SUPPLIED_LFEA_FILE'],'QUALIFIED_LFEA_REVIEW_EVIDENCE_ONLY');}
function settingsRow(){return row(CONSUMER_IDS.SETTINGS,'Settings','Review, propose, validate and explicitly apply the immutable engineering settings profile.',IMPLEMENTATION_STATUS.IMPLEMENTED,[],[],['RESET_PROPOSAL','RESET_TO_APPROVED_DEFAULTS','APPLY_SETTINGS_PROFILE'],'EXPLICIT_TRANSACTIONAL_SETTINGS_AUTHORITY_ONLY');}
function qaRow(){return row(CONSUMER_IDS.QA,'QA','Review current runtime contract availability, validity, identity, readiness, blockers, diagnostics and retained qualification evidence.',IMPLEMENTATION_STATUS.IMPLEMENTED,[],allContracts(),['EXPORT_QA_EVIDENCE','REFRESH_QA_EVIDENCE'],'READ_ONLY_RUNTIME_EVIDENCE_ASSESSMENT_ONLY');}
function recoveryRow(id,label,purpose){return row(id,label,purpose,IMPLEMENTATION_STATUS.RECOVERY_PENDING,[],[],[],'NO_ENGINEERING_CLAIMS');}
function loadCalcRow(version){if(version===1)return row(CONSUMER_IDS.LOAD_CALC,'Load Calc','Future reusable load-calculation consumer.',IMPLEMENTATION_STATUS.NOT_IMPLEMENTED,['loadCaseSet','loadPrimitiveSet','modelLoadReadinessAudit','sharedModel'],['supportLoadScreening','verticalLoadPathModel'],[],'NO_ENGINEERING_CLAIMS');if(version===11)return row(CONSUMER_IDS.LOAD_CALC,'Edit, Topo fix and Load Calc','Import Project Data and masters, then calculate source-traceable empirical vertical support reactions.',IMPLEMENTATION_STATUS.IMPLEMENTED,['sharedModel'],['loadCaseSet','loadPrimitiveSet','modelLoadReadinessAudit','verticalLoadPathModel','supportLoadScreening','supportLoadScreeningAudit'],['IMPORT_PROJECT_DATA_PROFILE','IMPORT_MASTER_DATA','CALCULATE_EMPIRICAL_SUPPORT_LOADS','SELECT_SUPPORT_SITE'],'PROJECT_DATA_GOVERNED_EMPIRICAL_VERTICAL_REACTIONS_ONLY');return row(CONSUMER_IDS.LOAD_CALC,'Load Calc','Review exact W10.4 model-load evidence and optional W10.5 tributary screening.',IMPLEMENTATION_STATUS.IMPLEMENTED,['sharedModel','loadCaseSet','loadPrimitiveSet','modelLoadReadinessAudit'],['verticalLoadPathModel','supportLoadScreening','supportLoadScreeningAudit'],['REBUILD_MODEL_LOADS','EXPORT_MODEL_LOADS','REBUILD_VERTICAL_LOAD_PATHS','RUN_TRIBUTARY_SCREENING','EXPORT_TRIBUTARY_SCREENING'],'MODEL_LOAD_EVIDENCE_AND_OPTIONAL_TRIBUTARY_SCREENING_ONLY');}
function threeDCalcRow(version){if(version<3)return row(CONSUMER_IDS.THREE_D_CALC,'3D Calc','Future three-dimensional calculation consumer.',IMPLEMENTATION_STATUS.NOT_IMPLEMENTED,['restraintCapabilityModel','sharedModel','supportAttachmentModel','topologyGraph'],['loadPrimitiveSet','verticalBeamSolution'],[],'NO_ENGINEERING_CLAIMS');return row(CONSUMER_IDS.THREE_D_CALC,'3D Calc','Review exact model, topology, support/restraint and optional vertical-beam evidence.',IMPLEMENTATION_STATUS.IMPLEMENTED,['sharedModel','topologyGraph','topologyAudit','supportAttachmentModel','supportAttachmentAudit','restraintCapabilityModel','restraintCapabilityAudit'],['loadPrimitiveSet','flexuralPropertyProjection','verticalBeamModel','verticalBeamSolution','verticalBeamSolverAudit'],['EXPORT_SHARED_MODEL','REBUILD_TOPOLOGY_EXACT','EXPORT_TOPOLOGY','REBUILD_SUPPORT_EVIDENCE','EXPORT_SUPPORT_RESTRAINT','REBUILD_VERTICAL_BEAM_MODEL','SOLVE_VERTICAL_BEAM','EXPORT_VERTICAL_BEAM'],'MODEL_TOPOLOGY_RESTRAINT_AND_OPTIONAL_VERTICAL_BEAM_EVIDENCE_ONLY');}
function pipeSolverRow(version){if(version<4)return row(CONSUMER_IDS.PIPE_SOLVER,'Pipe Solver','Future piping solver consumer.',IMPLEMENTATION_STATUS.NOT_IMPLEMENTED,['loadCaseSet','loadPrimitiveSet','restraintCapabilityModel','sharedModel','supportAttachmentModel','topologyGraph'],['flexuralPropertyProjection','verticalBeamModel'],[],'NO_ENGINEERING_CLAIMS');return row(CONSUMER_IDS.PIPE_SOLVER,'Pipe Solver','Review and request the existing guarded pipe-screening capability.',IMPLEMENTATION_STATUS.IMPLEMENTED,['sharedModel','topologyGraph','topologyAudit'],['supportAttachmentModel','restraintCapabilityModel','loadCaseSet','loadPrimitiveSet','flexuralPropertyProjection','verticalBeamModel','verticalBeamSolution'],['OPEN_PIPE_SCREENING_SESSION','UPDATE_PIPE_SCREENING_OVERRIDE','RESET_PIPE_SCREENING_SESSION','RUN_PIPE_SCREENING','CLOSE_PIPE_SCREENING_SESSION','SELECT_ANALYSIS_LEDGER_ENTRY','EXPORT_ANALYSIS_LEDGER'],'EXISTING_BENCHMARKED_SIMPLIFIED_2D_SCREENING_ONLY');}
function registrySchema(version){return[null,WORKSPACE_CONSUMER_REGISTRY_SCHEMA,WORKSPACE_CONSUMER_REGISTRY_V2_SCHEMA,WORKSPACE_CONSUMER_REGISTRY_V3_SCHEMA,WORKSPACE_CONSUMER_REGISTRY_V4_SCHEMA,WORKSPACE_CONSUMER_REGISTRY_V5_SCHEMA,WORKSPACE_CONSUMER_REGISTRY_V6_SCHEMA,WORKSPACE_CONSUMER_REGISTRY_V7_SCHEMA,WORKSPACE_CONSUMER_REGISTRY_V8_SCHEMA,WORKSPACE_CONSUMER_REGISTRY_V9_SCHEMA,WORKSPACE_CONSUMER_REGISTRY_V10_SCHEMA,WORKSPACE_CONSUMER_REGISTRY_V11_SCHEMA,WORKSPACE_CONSUMER_REGISTRY_V12_SCHEMA][version];}
function row(consumerId,label,purpose,implementationStatus,required,optional,actions,policy){return{consumerId,label,purpose,implementationStatus,requiredContractKeys:required,optionalContractKeys:[...new Set([...required,...optional])].sort(),allowedActions:actions,engineeringClaimPolicy:policy};}
function normalizeDescriptor(value){if(!stringValue(value.purpose)||!stringValue(value.engineeringClaimPolicy))throw new TypeError('Consumer descriptor text is required.');return deepFreeze({...value,requiredContractKeys:[...value.requiredContractKeys].sort(),optionalContractKeys:[...value.optionalContractKeys].sort(),allowedActions:[...value.allowedActions].sort()});}
function validateExact(value,expected,schema){const errors=[];if(value?.schema!==schema)errors.push(`Invalid ${schema} schema.`);if(canonicalStringify(value)!==canonicalStringify(expected))errors.push(`${schema} does not match its closed canonical descriptor set.`);return deepFreeze({ok:!errors.length,errors});}
function allContracts(){return['activeModelCalculationPackage','activeModelCalculationReport','flexuralPropertyProjection','loadCaseSet','loadPrimitiveSet','modelCalculationLedger','modelLoadReadinessAudit','restraintCapabilityAudit','restraintCapabilityModel','sharedModel','supportAttachmentAudit','supportAttachmentModel','supportLoadScreening','supportLoadScreeningAudit','topologyAudit','topologyGraph','verticalBeamModel','verticalBeamSolution','verticalBeamSolverAudit','verticalLoadPathModel'];}
function reportsRequired(){return['activeModelCalculationPackage','activeModelCalculationReport','modelCalculationLedger'];}function reportsOptional(){return['supportLoadScreening','verticalBeamSolution'];}function workspaceActions(){return['CLEAR_DATASET','CREATE_CALCULATION_PACKAGE','EXPORT_ARCHIVED_PACKAGE','IMPORT_DATASET','RUN_SCREENING','SELECT_ARCHIVED_PACKAGE','SELECT_ENTITY','SOLVE_VERTICAL_BEAM'];}function reportsActions(){return['EXPORT_ARCHIVED_PACKAGE','SELECT_ARCHIVED_PACKAGE'];}
